PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS empresas(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	
	regiao TEXT NOT NULL,	
	nome TEXT NOT NULL,
	url TEXT
);

CREATE TABLE IF NOT EXISTS linhas(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_empresa INTEGER NOT NULL,

	codigo TEXT NOT NULL,
	nome TEXT NOT NULL,
	detalhe TEXT ,
	url TEXT ,

	eh_executivo BOOLEAN DEFAULT 0,

	FOREIGN KEY(id_empresa) REFERENCES empresas(id)
);

CREATE TABLE IF NOT EXISTS horarios(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_empresa INTEGER NOT NULL,
	id_linha INTEGER NOT NULL,
	
	dia TEXT NOT NULL,
	sentido TEXT,
	hora TEXT NOT NULL,

	FOREIGN KEY(id_empresa) REFERENCES empresas(id),
	FOREIGN KEY(id_linha) REFERENCES linhas(id)
);
